version: '3'

services:
  cloner:
    build: "./cloner"
    command: "python -u main.py"
    environment:
      - REPO_BASE_LOCATION=$REPO_BASE_LOCATION
    depends_on:
      - rabbitmq
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
